Attribute VB_Name = "IconConstants"
'@Folder "MVVM.Model.Constants"
Option Explicit
Public Const MSO_APP As String = "icoXlApp"
Public Const MSO_EMPTY As String = "icoDataEmpty"
Public Const MSO_ERRORS As String = "icoError"
Public Const MSO_FORMULA As String = "icoFormula"
Public Const MSO_ITEM As String = "icoSelCell"
Public Const MSO_KEY_COL As String = "icoKey"
Public Const MSO_LINK As String = "icoLink"
Public Const MSO_LO As String = "icoXlTable"
Public Const MSO_LO_404 As String = "icoNotFound"
Public Const MSO_LO_HID As String = "icoXlSheetHidden"
Public Const MSO_LO_PRT As String = "icoXlSheetProtected"
Public Const MSO_LO_SEL As String = "icoXlTableTick"
Public Const MSO_SELECTED As String = "icoKey"
Public Const MSO_TYPE_BOOLEAN As String = "icoDataBoolean"
Public Const MSO_TYPE_CURRENCY As String = "icoDataCurrency"
Public Const MSO_TYPE_DATE As String = "icoDataDate"
Public Const MSO_TYPE_LONG As String = "icoDataLong"
Public Const MSO_TYPE_STRING As String = "icoDataString"
