Attribute VB_Name = "IconConstants"
'@Folder "MVVM.Resources.Constants"
Option Explicit

Public Const MSO_ACCEPT As String = "icoAccept"
Public Const MSO_EXCEL_APP As String = "icoXlApp"
Public Const MSO_AUTO_SUM As String = "icoAutoSum"
Public Const MSO_EMPTY As String = "icoDataEmpty"
Public Const MSO_ERROR As String = "icoError"
Public Const MSO_FORMULA As String = "icoFormula"
Public Const MSO_CELL As String = "icoSelCell"
Public Const MSO_KEY As String = "icoKey"
Public Const MSO_LINK As String = "icoLink"
Public Const MSO_TABLE As String = "icoXlTable"
Public Const MSO_NOT_FOUND As String = "icoNotFound"
Public Const MSO_SHEET_HIDDEN As String = "icoXlSheetHidden"
Public Const MSO_SHEET_PROTECTED As String = "icoXlSheetProtected"
Public Const MSO_TABLE_TICK As String = "icoXlTableTick"
Public Const MSO_TYPE_BOOLEAN As String = "icoDataBoolean"
Public Const MSO_TYPE_CURRENCY As String = "icoDataCurrency"
Public Const MSO_TYPE_DATE As String = "icoDataDate"
Public Const MSO_TYPE_LONG As String = "icoDataLong"
Public Const MSO_TYPE_STRING As String = "icoDataString"
Public Const MSO_WARNING As String = "icoWarning"
