VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IValueConverter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("MVVM.Infrastructure.Abstract")
Option Explicit

Public Sub Convert(ByVal Source As Object, ByVal Target As Object)
End Sub

Public Sub ConvertBack(ByVal PropertyBinding As IPropertyBinding)
End Sub

Public Sub Initialize(ByVal Target As Object)
End Sub
