VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IValueConverter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Interface
'@Folder "Abstractions"
Option Explicit

Public Sub Convert(ByVal Control As Object, ByVal Data As Object)
End Sub

Public Sub Initialize(ByVal Control As Object)
End Sub
